name: CMake

on: 
  push:
    paths: 
      - ".github/workflows/test-cmake.yml"
      - "dist/**"
      - "action.yml"
      - "test/**"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016]

    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      uses: ./
      id: install-boost
      with:
        boost_version: 1.73.0

    - name: Configure CMake
      shell: bash
      working-directory: test
      run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Build
      working-directory: test/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
