name: test

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: Install boost
        uses: ./
        id: install-boost
        with:
          boost_version: 1.73.0
      - run: echo ${{ steps.install-boost.outputs.BOOST_ROOT }}
        shell: bash
      - run: echo ${{ steps.install-boost.outputs.BOOST_VER }}
        shell: bash
